In [1]:
#1.list

In [2]:
import numpy as np
import pandas as pd
list1 = [10,20,30,40,50,60,70,80,90,100]
fruits=["Apple","Banana","Cherry","Orange"]
print("list:", list1)
print("Fruits:" , fruits)

list: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
Fruits: ['Apple', 'Banana', 'Cherry', 'Orange']


In [3]:
#2.Arrays
list2 = [1,2,3,5,7,9,23,45,78]
list3 = [4,5,7,9,3,56,89]
array1 = np.array(list2)
array2 = np.array(list3)
print("Array:" , array1)
print("Array:" , array2)


Array: [ 1  2  3  5  7  9 23 45 78]
Array: [ 4  5  7  9  3 56 89]


In [4]:
#3. Identify their type using type()

print("Type of list1:" , type(list))
print("Type of fruits:" , type(fruits))
print("Type of array1:", type(array1))
print("Type of array2:",type(array2))

Type of list1: <class 'type'>
Type of fruits: <class 'list'>
Type of array1: <class 'numpy.ndarray'>
Type of array2: <class 'numpy.ndarray'>


In [5]:
#4.Perform mathematical operations on these datasets created - multiplication, division,poweroff Performing mathematical operations

import numpy as np

# Example arrays
array3 = np.array([11, 12, 13, 14])
array4 = np.array([55, 66, 77, 88])

# Perform mathematical operations
multiplication = array3 * array4
division = np.divide(array3, array4)  # Handles division by zero safely
poweroff = array3 ** 4

# Print results
print("Multiplication:\n", multiplication)
print("Division:\n", division)
print("Power of 2:\n", poweroff)


Multiplication:
 [ 605  792 1001 1232]
Division:
 [0.2        0.18181818 0.16883117 0.15909091]
Power of 2:
 [14641 20736 28561 38416]


In [8]:
import numpy as np

# Example arrays
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

# Pad array2 with zeros to match the shape of array1
array2_padded = np.pad(array2, (0, array1.shape[0] - array2.shape[0]), 'constant', constant_values=0)

# Perform addition
add_result = array1 + array2_padded

# Print results
output = f"Addition of Two:\n{array1} + {array2_padded} = {add_result}"
print(output)

Addition of Two:
[1 2 3 4] + [5 6 7 8] = [ 6  8 10 12]


In [9]:
#6. implement np.sin(), log(), log2(), np.exp())
array3 = np.array([1, 2, 3, 4])
sin_result = np.sin(array3)
log_result = np.log(array3)
log2_result = np.log2(array3)
exp_result = np.exp(array3)
print(f"Sin Result: {sin_result}")
print(f"Log Result: {log_result}")
print(f"Log2 Result: {log2_result}")
print(f"Exp Result: {exp_result}")

Sin Result: [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
Log Result: [0.         0.69314718 1.09861229 1.38629436]
Log2 Result: [0.        1.        1.5849625 2.       ]
Exp Result: [ 2.71828183  7.3890561  20.08553692 54.59815003]
